### ISSUE TITLE
The evalution protocol?

### ISSUE THREAD

**Issue by GuHY777** [prismformore/expAT#3]
sorry to disturb you. Is the evaluation method of SYSU-MM01 in the paper different from the evaluation method in the code? In the code, the evaluation method uses the method such as Market1501, but the official evaluation method is the average of the results of ten random divisions.

Can this part of the evaluation method give the corresponding code? thank you very much!

**Comment by prismformore** [comment]
This code DOES the average of the results of ten random runs. Here is the code where we control the repeated test times:

https://github.com/prismformore/expAT/blob/716c2a79db63b52cd2256edbffcc958e7e742de0/rgbir_exp/codes/main.py#L324

Hope this can help you.

**Comment by prismformore** [comment]
The problem seems solved so I close this issue. Feel free to comment if you have further questions.
