### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by syh-hue** [prismformore/expAT#4]
This is a good job. Figure 3 in the paper where is the code for visualizing expat loss? comparison with Triplet loss on the data set SYSU-MM01.

**Comment by prismformore** [comment]
@syh-hue Hi, thank you for your interest in our work. For visualization of feature embeddings, we use t-SNE. We first calculate the feature embeddings of each single image in the target dataset and then use t-SNE. The usage of t-SNE is simple and please refer to this helpful repository: https://github.com/CannyLab/tsne-cuda

**Comment by syh-hue** [comment]
> @syh-hue您好，感谢您对我们的工作感兴趣。对于特征嵌入的可视化，我们使用 t-SNE。我们首先计算目标数据集中每个单个图像的特征嵌入，然后使用 t-SNE。t-SNE 的使用很简单，请参考这个有用的存储库：[https](https://github.com/CannyLab/tsne-cuda) : [//github.com/CannyLab/tsne-cuda](https://github.com/CannyLab/tsne-cuda)

ok thanks, Let me have a try.
